//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Metro_Operation
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]

        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            Thread.CurrentThread.CurrentCulture=CultureInfo.InvariantCulture;
            Thread.CurrentThread.CurrentUICulture=CultureInfo.InvariantCulture;

            // مرحله ۱: نمایش Splash
            //using (var splash=new SplashForm())
            //{
            //    var result=splash.ShowDialog();
            //    if (result != DialogResult.OK)
            //        return; // اگر اسپلش موفق نبود، خروج
            //}

           
            // مرحله ۲: ورود کاربر
            using (var login=new LoginForm())
            {
                if (login.ShowDialog() == DialogResult.OK)
                {
                    // مرحله ۳: اجرای فرم اصلی
                    Application.Run(new MainForm());
                }
            }
        }
    }
}
